### PR TITLE
Parse user, channel, and role mentions.

### PR DESCRIPTION
**Pull request by AL1L**
I did test this.

### CODE REVIEW

**Comment by AL1L** [comment]
I put the parsing in its own method so that in the future when you support message editing you can use that method.

**Comment by AL1L** [comment]
@jaketr00 what's your Discord? Mine is AL_1#0001

**Comment by jaketr00** [comment]
@AL1L nice you got #0001 too, mine is Jaker#0001

**Comment by AL1L** [comment]
Just noticed that I never actually declared `mentionRegex`

**Pull request merged**
