### PR TITLE
Fixes and additions!

### PR DESCRIPTION
**Pull request by Kio-td**
So! I fixed a few things, I think it looks really good! >3<

### CODE REVIEW

**Comment by AL1L** [comment]
Actually, I just realized @Kio-td, the messages are reversed

**Comment by Kio-td** [comment]
Huh - I was just using the code that was already in there - might've been messed up during that time.

The most basic fix would be to reverse the messages and pop them in like that.

**Comment by Kio-td** [comment]
Oh, I figured it out, I'll edit that

**Comment by Kio-td** [comment]
@AL1L, that should fix it.

**Comment by AL1L** [comment]
Hey @Kio-td what's your Discord?

**Comment by Kio-td** [comment]
OOHLOOKTHISISTOTALLYNOTAFAKEDISCORD#9999

**Comment by jaketr00** [comment]
ive been dead for a while but i just merged it, it runs well for me

**Pull request merged**
